#version: '3.8'
name: nginx-proxy
services:
  nginx-proxy:
    image: jwilder/nginx-proxy:latest
    container_name: proxy_nginx
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./nginx-custom.conf:/etc/nginx/conf.d/custom-settings.conf"
    ports:
      - "80:80"
    restart: 'always'
    networks:
      - default

networks:
  default:
    name: nginx-proxy_net
    driver: bridge
